[package]
name = "elden_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
scraper = "0.11.0"
regex = "1.7.1"
lazy_static = "1.4.0"
csv = "1.1.6"
serde = "1.0.152"